sudo: required

services:
  - docker

language: java

script: mvn clean package

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  provider: script
  script: docker push acuitybotting/service-bot-control
  on:
    branch: master