sudo: required

services:
  - docker

language: java

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"

deploy:
  provider: script
  script: docker push acuitybotting/service-bot-control
  on:
    branch: master